import XCTest
@testable import AgentPetCore

/// 纯函数 `LocalSummarizer.summarize`:会话主题=第一条真实用户指令(开场任务)。
final class LocalSummarizerTests: XCTestCase {

    func test_firstUserInstruction_isTheSessionTopic() {
        // 会话主题=开场任务(第一条真实指令),不是最后一条活动。
        let turns = [
            ConversationTurn(role: "user", text: "修复登录 bug", stopReason: nil),
            ConversationTurn(role: "assistant", text: "好的，我来看看", stopReason: "end_turn"),
            ConversationTurn(role: "user", text: "顺便加个测试", stopReason: nil),
            ConversationTurn(role: "assistant", text: "已加测试并跑通", stopReason: "end_turn"),
        ]
        let s = LocalSummarizer.summarize(turns: turns)
        XCTAssertTrue(s.contains("修复登录 bug"), "应取开场任务(第一条),得: \(s)")
        XCTAssertFalse(s.contains("顺便加个测试"), "不应是最后一条活动: \(s)")
    }

    func test_truncatesLongText() {
        let long = String(repeating: "字", count: 200)
        let s = LocalSummarizer.summarize(turns: [ConversationTurn(role: "user", text: long, stopReason: nil)],
                                          maxLen: 20)
        XCTAssertLessThanOrEqual(s.count, 100)
        XCTAssertTrue(s.contains("…"), "过长应截断加省略号")
    }

    func test_empty_returnsPlaceholder() {
        XCTAssertEqual(LocalSummarizer.summarize(turns: []), "（无可总结内容）")
    }

    func test_onlyAssistant_stillSummarizes() {
        let s = LocalSummarizer.summarize(turns: [ConversationTurn(role: "assistant", text: "分析完成", stopReason: "end_turn")])
        XCTAssertTrue(s.contains("分析完成"))
    }

    // 评审修复（AI m6）：不可信文本消毒——控制字符/bidi 覆盖符被滤除，stopReason 也限长。
    func test_sanitizes_controlAndBidiChars() {
        let evil = "正常\u{202E}倒序欺骗\u{0007}响铃"
        let s = LocalSummarizer.summarize(turns: [ConversationTurn(role: "user", text: evil, stopReason: nil)])
        XCTAssertFalse(s.contains("\u{202E}"), "RTL 覆盖符必须滤除")
        XCTAssertFalse(s.contains("\u{0007}"), "控制字符必须滤除")
        XCTAssertTrue(s.contains("正常"))
    }

    // 跳过 harness 注入的系统消息(<task-notification>/<system-reminder>/<local-command-*>/
    // [SYSTEM NOTIFICATION.../Caveat:...):这些在 jsonl 里也是 user 角色,但不是真实用户指令。
    func test_skipsInjectedSystemMessages_picksRealInstruction() {
        let turns = [
            ConversationTurn(role: "user", text: "帮我修复登录超时的 bug"),
            ConversationTurn(role: "assistant", text: "好的,我来看看"),
            ConversationTurn(role: "user", text: "<task-notification> <task-id>a2c77337</task-id> <tool-use-id>x</tool-use-id>"),
        ]
        let s = LocalSummarizer.summarize(turns: turns)
        XCTAssertTrue(s.contains("修复登录超时"), "应取真实指令,而非注入的 task-notification: \(s)")
        XCTAssertFalse(s.contains("task-notification"), "注入内容不得进摘要: \(s)")
    }

    func test_skipsVariousInjectionMarkers() {
        for injected in ["<system-reminder>提醒</system-reminder>",
                         "<local-command-stdout>输出</local-command-stdout>",
                         "[SYSTEM NOTIFICATION - NOT USER INPUT] 后台事件",
                         "Caveat: The messages below were generated by the user while running local commands."] {
            let turns = [
                ConversationTurn(role: "user", text: "真实指令ABC"),
                ConversationTurn(role: "user", text: injected),
            ]
            let s = LocalSummarizer.summarize(turns: turns)
            XCTAssertTrue(s.contains("真实指令ABC"), "被 \(injected.prefix(20)) 干扰: \(s)")
        }
    }

    /// 全是注入消息时,退化到取最后一条(有内容总比空好),但不崩。
    func test_allInjected_stillProducesSomething() {
        let turns = [ConversationTurn(role: "user", text: "<task-notification>only</task-notification>")]
        let s = LocalSummarizer.summarize(turns: turns)
        XCTAssertFalse(s.isEmpty)
    }

    func test_stopReason_alsoTruncatedAndSanitized() {
        let longReason = String(repeating: "x", count: 500) + "\u{202E}"
        let s = LocalSummarizer.summarize(
            turns: [ConversationTurn(role: "assistant", text: "", stopReason: longReason)], maxLen: 20)
        XCTAssertFalse(s.contains("\u{202E}"))
        XCTAssertLessThan(s.count, 60, "stopReason 同样限长")
    }

    func test_skipsTrivialOpening_picksFirstRealTask() {
        // 开场是 "hello" 寒暄 → 跳过,取下一条真正的任务。
        let turns = [
            ConversationTurn(role: "user", text: "hello"),
            ConversationTurn(role: "assistant", text: "你好,有什么可以帮你?"),
            ConversationTurn(role: "user", text: "帮我把 apet 的通知改成静默模式"),
        ]
        let out = LocalSummarizer.summarize(turns: turns)
        XCTAssertTrue(out.contains("静默模式"), "应跳过 hello 取真任务,得: \(out)")
        XCTAssertFalse(out.contains("hello"), "寒暄不该是摘要: \(out)")
    }
    func test_allTrivial_fallsBackToFirstUser() {
        let turns = [ConversationTurn(role: "user", text: "hi"), ConversationTurn(role: "user", text: "ok")]
        let out = LocalSummarizer.summarize(turns: turns)
        XCTAssertEqual(out, "hi", "全寒暄时退化到第一条,总比空好")
    }
}
